### ISSUE TITLE
Typing of get() does not include computed state

### ISSUE THREAD

**Issue by geirsagberg** [chrisvander/zustand-computed#15]
Given the following code:

```ts
interface State {
  a: number
  b: number
}

function computeState({ a, b }: State) {
  return {
    c: a + b,
  }
}

const useState = create<State>()(
  computed(
    immer((set, get) => ({
      a: 1,
      b: 2,
      incrementAndLog: () => {
        set((state) => {
          state.a += 1
          state.b += 1
        })
        // Error: Property 'c' does not exist on type 'State'
        const { c } = get()
        console.log(c)
      },
    })),
    computeState
  )
)
```

Is there a way to make `get()` automatically include the computed properties?

**Comment by geirsagberg** [comment]
The code works as expected; property `c` exists, only the typing does not match. I know I can workaround with `get() as ComputedState` but would be nice if this was not necessary.

**Comment by chrisvander** [comment]
The best way would be to make the root `create` call (which determines the `get()` function's typing be templated with some `FullState` type, perhaps:
```ts
type FullState = State & ReturnType<typeof computeState>
```

**Comment by geirsagberg** [comment]
With `type FullState = State & ReturnType<typeof computeState>` I get errors because `create<FullState>` expects me to return values for the computed state.

Closest workaround I could find was:

    type FullState = State & Partial<ReturnType<typeof computeState>>

Downside of this is that all computed values will be potentially `undefined` when used in the `create` call.

**Comment by chrisvander** [comment]
Hey, @geirsagberg, sorry to take so long to get back to you. Unfortunately, with Immer, Immer derives the type for it's `SetState` from `GetState`, and the `ComputedStore` is explicitly left out of `SetState` for now. Without Immer, `get()` has the correct type in version 1.4.0.

**Comment by chrisvander** [comment]
One other suggestion, you could try swapping Immer & computed. Otherwise, closing this issue.

**Comment by chrisvander** [comment]
Hey, figured out the issue. Middleware types were not cascading down appropriately. I would suggest trying out [version 2.0](https://github.com/chrisvander/zustand-computed/releases/tag/v2.0.0) and see if the new pattern brings the types through appropriately. I also opened (#2696)[https://github.com/pmndrs/zustand/pull/2696] to address the aforementioned issue with Immer deriving the `setState` type from `getState`. Let me know if that works.
