### ISSUE TITLE
I'm using a combination of immer middleware and typescript, but my computedState type doesn't exist!

### ISSUE THREAD

**Issue by LiuCaptain** [chrisvander/zustand-computed#24]
Here is my code：

```javascript
import { StoreApi, useStore } from 'zustand';
import { createStore } from 'zustand/vanilla';
import { devtools, persist, subscribeWithSelector } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';
import computed from 'zustand-computed';
import baseSlice from './baseSlice';
import userInfoSlice, { userInfoComputedState } from './userInfoSlice';
import type { BaseSlice } from './baseSlice';
import type { UserInfoSlice, UserInfoComputedState } from './userInfoSlice';

interface RootSlice {
  _hasHydrated: boolean;
  setHasHydrated: (state: boolean) => void;
}

type ComputedState = UserInfoComputedState;

export type BoundStore = RootSlice & BaseSlice & UserInfoSlice;

const computedState = (state): ComputedState => ({
  ...userInfoComputedState(state)
});

const createBoundStore = () => {
  return createStore<BoundStore & ComputedState>()(
    devtools(
      subscribeWithSelector(
        persist(
          computed(
            immer((set, get, store) => ({
              ...baseSlice(set),
              ...userInfoSlice(set, get),
              _hasHydrated: false,
              setHasHydrated(state) {
                set({ _hasHydrated: state });
              }
            })),
            computedState
          ),
          {
            name: 'boundStore',
            onRehydrateStorage: () => (state) => {
              state?.setHasHydrated(true);
            }
          }
        )
      )
    )
  );
};
```

The following screenshot shows the properties of my computedState:
![image](https://github.com/user-attachments/assets/1e673426-27d1-4cdc-b3cb-35f18e5f002f)

I merged the type of computedState
![image](https://github.com/user-attachments/assets/a307c526-abf3-4351-b415-b6debc80c361)

but!!!
![image](https://github.com/user-attachments/assets/04d4e81b-b592-469a-b25e-c721db99070f)

I am configuring this according to the documentation, and the computed properties are fetched as expected, just the typescript exception, what should I do to fix this typescript error?

**Comment by chrisvander** [comment]
Because your create call is `createStore<BoundStore & ComputedState>`, the innermost middleware (immer in this case) is expecting that the initial store you return include the computed state.

Try using `createStore<BoundStore>`.

**Comment by LiuCaptain** [comment]
I'm getting typescript errors when I do it your way.
![image](https://github.com/user-attachments/assets/9c46bbfa-0c1e-4012-bb5c-5e9e294e5bad)
But the code can get the value of the property normally

**Comment by LiuCaptain** [comment]
PS. You can see the ComputedState in my first screenshot

**Comment by chrisvander** [comment]
Could you provide a reproduction in a TypeScript playground? [This is the closest I got](https://www.typescriptlang.org/play/?noImplicitAny=false&ts=5.5.4#code/JYWwDg9gTgLgBAbzgYygUwIYzXAvnAMyghDgCIAvAVwGcYMA7AEzIChRJZE4m0A3GBAgAbGgBo4NKgCMaqYNLQB1YDAAWAZTTC0yQVAlg0UGsDp5CxUpVr1mAehDAmTHQHcM6Nh2jwkoEGMLIhJyajpGJkdnVzQPdHsA429wX25kEjAqbCZgqzDbSIBaDPBstBZWVhgATyM4DX0cAF5EVjgUCCoGGAAuOAYqEEUodrhgBmR+gAoASjhmgD44PghnMd4puDmF5dX13Cra+oBhTPKmRugWto6M7pgNAEd+weHjVkPWAm69YAgGJ0ythGlg0NMIth+ld0LN+mdgRUYTgEGN0DAqFBAaiOncuj1nv1IWgAHT3HpwABUlLgACYxGNDl8MgxzLQ0MiFih0GCADzIxZzaYbfiCEQ0YW4yQyORQBTKVSabS6fSSqVwIwmMwwNXqoFZHK6vXjECBKD8poSADaVpsEQcvAEQlEZAkDH4xgAuta7XYolJZPJFCp1FodHpoK6Bh6oN64Lbwn77JrTHQo90ANYMCBuBhx23INRymh8SLGeyJ4qlA0VKMImuXJqe-MJwoOJJQKPuvhez2CiFoGDzJbbHHGqXkvpwACMDPHUomWx2I5og+mEPo2GHy2mSEnRM3pMncAA1DO8LMJAQMKI0BIAOSL++Xsbzni6GbbyRrjdgr+7zoHgPMEyXxeAinPXBL0IG9VwfTZnznecoJfN9q3KUFsFfdVUONMdxwYDBAn6MhsDTbCpUOPVZmwmiOhomjWBZcw6GuLl2WRX9sF2SRD1Ah5nlmIA), but as you can see, the store is properly returning the computed state.

Additionally, you could try explicitly typing the order of mutators on the Immer middleware the way I do in that playground. It appears that, when contained within the `computed` middleware, the mutators get lost.

**Comment by chrisvander** [comment]
Okay, figured out the issue with the Zustand maintainer. Immer itself may still allow you to "set" the computed state, which should not be possible, but I've opened [#2696](https://github.com/pmndrs/zustand/pull/2696) to address that issue on Zustand's side. As far as the type inference goes, I'm releasing version 2.0.0 of `zustand-computed` which should address the type inference issues by using a new pattern, `createComputed`, which will nicely bundle up the `computeState` function and any appropriate options and return a middleware for you to use.

**Comment by LiuCaptain** [comment]
OK， thanks, I will upgrade to zustand-computed

**Comment by LiuCaptain** [comment]
I upgraded zustand-computed to version 2.0 and still get typescript type errors.
![image](https://github.com/user-attachments/assets/49cc69bf-c0d3-4044-bce4-fd4fc99035e3)
![image](https://github.com/user-attachments/assets/2a0512a6-35af-4a28-91eb-5bb05a606806)

Since I'm using zustand-computed in combination with immer middleware and typescript, can you write an example that combines immer and typescripty with zustand-computed, I'd like to see the example you've written, or can you update your github docs, thank you!
