### ISSUE TITLE
Order of middleware when using computed with immer (plus nested state)

### ISSUE THREAD

**Issue by tchock** [chrisvander/zustand-computed#36]
Hello,

I'm trying to compose the `computed` middleware with `immer` and in the README example it shows the middleware being in the order of `immer(computed(...))`. But when I do that the state is an immer `Proxy` and the immer middleware expects the state to be modified by setting the value directly instead of returning a the whole state object. 

When I change the order to `computed(immer())` it works, but then with the return pattern.

I would love to have support for the `immer` pattern as I have nested state objects. Something like this:

```js
const computed = createComputed((state) => {
  state.basket.total = calculateBasketTotal(state);
});
```

The above example fails because it's not returning anything and `zustand-computed` is trying to go through the keys of the returned object. 

Because of the nested state I need to do something like this:
```js
const computed = createComputed((state) => ({
  basket: {
    ...state.basket,
    total: calculateBasketTotal(state),
  },
}));
```

If the immer pattern is not working, maybe a `merge` with existing state would work? So that I could do this (and it would merge it with the existing `basket` object):

```js
const computed = createComputed((state) => ({
  basket: {
    total: calculateBasketTotal(state),
  },
}));
```

I know this is multiple things in one issue. If one of the approaches would be feasable to you I can also make a new one describing only this approach.

Otherwise for the meantime maybe update the readme with the right order and show a sample content for the compose function, so it's clear it expects a return value and doesn't use the `immer` modification approach.

**Comment by tchock** [comment]
Just looked through solutions that could be used to do nested comparison for changes:
`proxy-compare` from dai-shi from the immer team would do exactly that :)

**Comment by chrisvander** [comment]
Hey Simon, appreciate the suggestion. I bet you could use Immer directly, as in, take the input from `createComputed`, call `produce` on it with an Immer recipe. A little more boilerplate but it seems overkill to integrate into this library. 

As for the ordering of the middlewares - I don't believe the Immer middleware should at all affect the way the `createComputed` function works, I don't think it is intended to assume any direct modifications would work. The Immer middleware is just expected to affect the get/set in the store creation itself. Let me know if there are issues there.
