### ISSUE TITLE
Zustand shallow import deprecation error

### ISSUE THREAD

**Issue by dabdine** [chrisvander/zustand-computed#4]
Zustand deprecated their default export for shallow. Using zustand-computed now produces these errors in development mode within the console:

![image](https://user-images.githubusercontent.com/1955040/215670355-e1b6d1f9-ca36-4fdd-a485-d8ca0790cae0.png)

See similar: https://github.com/wbkd/react-flow/discussions/2739

The problematic import is here: https://github.com/chrisvander/zustand-computed/blob/main/src/computed.ts#L2

**Comment by dabdine** [comment]
@chrisvander Looks like the dist on npmjs.org is using the old import statement still?

```bash
curl -s https://registry.npmjs.org/zustand-computed/-/zustand-computed-1.3.1.tgz --output - | tar xzfO - package/dist/computed.js | grep 'import shallow'
import shallow from "zustand/shallow";
```

**Comment by dabdine** [comment]
vs what you get if you clone and build locally:

```zsh 
➜  zustand-computed git:(main) npm run build

> zustand-computed@1.3.1 build
> tsc

➜  zustand-computed git:(main) grep 'import shallow' dist/computed.js
➜  zustand-computed git:(main) grep 'import { shallow }' dist/computed.js
import { shallow } from "zustand/shallow";
➜  zustand-computed git:(main) 
```

**Comment by chrisvander** [comment]
Oops, haven't gotten the hang of publishing packages yet. v1.3.2 was built properly.
