### ISSUE TITLE
Immer Support

### ISSUE THREAD

**Issue by zikphil** [chrisvander/zustand-computed#7]
Hello,

Do you have a working example that supports also using the immer middleware?

Thanks!

**Comment by chrisvander** [comment]
Are you working with TypeScript or JavaScript? Is there a specific part or issue that you're observing?

**Comment by chrisvander** [comment]
Hope [this example](https://github.com/chrisvander/zustand-computed#with-middleware) helps.

**Comment by zikphil** [comment]
Hello, yes it sure does :) Thank you so much.
